create table users (
    id bigint generated by default as identity primary key,
    login varchar(100),
    password varchar(100),
    surname varchar(100),
    name varchar(100),
    patronymic varchar(100),
    email varchar(100),
    phone varchar(100)
);